[toolchain]

[programs.localnet]
learn_solana_contract = "48zQM2WJcVtJYyv2gf2PqsCYawgFkEW9ZqrT61DTAZ7J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=ec39cc38-e55f-411b-98b1-019788078549"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
